services:
  postgres:
    image: 'postgres:16.5-alpine'
    container_name: railway-mgmt-postgres
    env_file:
      - ../.env
    ports:
      - '5433:5432'

#  railway-mgmt-api:
#    image: 'korn704/railway-mgmt-api:0.0.1'
#    container_name: railway-mgmt-api
#    ports:
#      - '8888:8888'
#    environment:
#      - DATABASE_URL=${DATABASE_URL}
#      - DATABASE_USER=${DATABASE_USER}
#      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
